<script setup>
import '@grapecity-software/spread-sheets/styles/gc.spread.sheets.excel2016colorful.css'
import "@grapecity-software/spread-sheets-designer/styles/gc.spread.sheets.designer.min.css"
import * as GC from "@grapecity-software/spread-sheets"
import "@grapecity-software/spread-sheets-print"
import "@grapecity-software/spread-sheets-shapes"
import "@grapecity-software/spread-sheets-slicers"
import "@grapecity-software/spread-sheets-pivot-addon"
import "@grapecity-software/spread-sheets-tablesheet"
// import "@grapecity-software/spread-sheets-ganttsheet"
// import "@grapecity-software/spread-sheets-reportsheet-addon"
import "@grapecity-software/spread-sheets-formula-panel"
import "@grapecity-software/spread-sheets-io"
import '@grapecity-software/spread-sheets-resources-zh'
import '@grapecity-software/spread-sheets-designer-resources-cn'
import "@grapecity-software/spread-sheets-designer"

GC.Spread.Sheets.Designer.LicenseKey = 'openapi.enfi.com.cn,684296222751797#B1tN9bTtiYidlMpN6cEZDdwRFb8QDcO94VPV7Zz54M4dVZYJEb0NXYqxUWlh5R554R65kTThmMNVzMIh5UmlEb98kdqNGT6kERvZlcmRnb72COHp4YYR7N7UDahRFNhV7MZ3yS6V5UwZkaGdzS8RjUkBTUolDZ7VHaYdzTS5UYalFe4c7b7U6YIZHVWhXdwg7cxNDM7FVYrpnahhVVpx4b7QUMFh5SrEVczEGTnNnVqZTTNJ4bTlGdkBFaxVTZyRUSolTalJFdk5UaGVDNDdFR9hnM6QGcHBFRx2yRyZnZ9h7MuV5NhhEZLdGTLlkRiR4T6o6KoFUUyIDcDJUQxckI0IyUiwiIFVkQ4Q4QFJjI0ICSiwSO8MTNxUTM8ETM0IicfJye35XX3JyUXJDNiojIDJCLicTMuYHIu3GZkFULyVmbnl6clRULTpEZhVmcwNlI0IiTis7W0ICZyBlIsISO5kTM7ADI8ADNwQjMwIjI0ICdyNkIsIiNwYDM4IDMyIiOiAHeFJCLi86Yu46bj9Sam9WZukGch9WZw3mI0IyctRkIsICuPWOrFWOkZmeica+rcaOgKa+ioeep7WusPieqBaevbWer8SuI0ISYONkIsIyN9cTM5cjMyIjN9IDN8YjI0ICZJJye0ICRiwiI34TUY5USVRXeSJVbJ3kaJRDNN3kWvNGdWpWZplXNwM6LapXZOhWb8NGa7cVeE3mbrkVcrtyS9xWQFBjZWZ4MmlFSoRVNwB5NONTSWp7arcGO7R4S9UWR1F9d'
GC.Spread.Sheets.LicenseKey = 'openapi.enfi.com.cn,268181326347254#B1XMdpmQYBzSa9UONF7SrETe99kdHdFdG5mSIdWTEVlUyplZkN5KM3GcLJzbalkMnVnM4R5dkZGSRJTa7RFdBNFcSRkcXFjakFzYolnQvZXYNFGb6Q6dGNTMHR7RXp7ZWlTRXBjbIVldsNkQrtGR05WT9c5QlZ6M5tEO98mSHZVWJRmTHNDR4lDax3yV7Y6ZwgjU5claEJmaxR4QPV5RwxESMNTY7Zma8ZDZVpmT6RGTXdlSPN4TmpWTP34Vi5ESIFHR4oHNaNDRlR4NS3kchpGZ7BVMkd6cxIDeElVOVhWRHRHWFxGO5FWVIhUOmtWY5VkaEpEOB5UMmtSd4cDZNJWWz9USoRESP3yVSpkSiojITJCLigjNzETR5UTNiojIIJCL6ADN4QDMwATN0IicfJye#4Xfd5nIVF4SRJiOiMkIsIyNx8idgMlSgQWYlJHcTJiOi8kI1tlOiQmcQJCLigTN9EzNwACOwQDM4IDMyIiOiQncDJCLiYDM6ADNyAjMiojIwhXRiwiIuNmLt36YukmZuVmLpBXYuVGcvJiOiMXbEJCLig1jlzahlDZmpnInm/KnmDoimvIqnX0tlL1jonagm71ml7KukLiOiEmTDJCLiQTNycDNzYjMzEDOxgjNyIiOiQWSiwSfdJSZsJWYUR7b6lGUislOicGbmJCLlNHbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TPRp6aGVENDFzdhZGSjp5aatWdshDUvZDcz2UOaxUTRllYQZ7QrMUdn5Ga6FXMNdTV9pkU5lzT056LYNUUkZ6YlFkb6JVZ6dhS5V'
GC.Spread.Common.CultureManager.culture("zh-cn")
window.GC = GC
</script>

<template>
  <RouterView />
</template>

<style>
.dragable {
  user-select: none;
  -webkit-app-region: drag;
}
.dragless {
  -webkit-app-region: no-drag;
}
</style>
